//------------------------------------------------------------------------------
// Author : Strix
// Github : https://github.com/KorStrix/SheetParser
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using UnityEngine;



public class global_Container : UnityEngine.ScriptableObject
{
    
    private static global_Container _instance;
    
    public List<global> listData;
    
    public Dictionary<EGlobalKey_string, string> mapData_Type_Is_string;
    
    public Dictionary<EGlobalKey_float, float> mapData_Type_Is_float;
    
    public Dictionary<EGlobalKey_int, int> mapData_Type_Is_int;
    
    public static global_Container instance
    {
        get
        {
               return _instance;
        }
    }
    
    public static void DoInit(global_Container pSingletonInstance, bool bIsUpdateChildAsset)
    {
          _instance = pSingletonInstance;
#if UNITY_EDITOR
           if(bIsUpdateChildAsset)
           {
              _instance.listData.Clear();
               Object[] arrObject = UnityEditor.AssetDatabase.LoadAllAssetRepresentationsAtPath(UnityEditor.AssetDatabase.GetAssetPath(_instance));
               for (int i = 0; i < arrObject.Length; i++)
                  _instance.listData.Add((global)arrObject[i]);
               if(Application.isPlaying == false)
               {
                   UnityEditor.EditorUtility.SetDirty(_instance);
                   UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(UnityEditor.SceneManagement.EditorSceneManager.GetActiveScene());
               }
           }
#endif
        _instance.Init_mapData_Type_Is_string();
        _instance.Init_mapData_Type_Is_float();
        _instance.Init_mapData_Type_Is_int();
    }
    
    private void Init_mapData_Type_Is_string()
    {
        var arrLocal = listData.Where(x => x.strType == "string");
        this.mapData_Type_Is_string = arrLocal.ToDictionary(p => p.eGlobalKey_string, p => (string)System.Enum.Parse(typeof(string), p.strValue));
    }
    
    private void Init_mapData_Type_Is_float()
    {
        var arrLocal = listData.Where(x => x.strType == "float");
        this.mapData_Type_Is_float = arrLocal.ToDictionary(p => p.eGlobalKey_float, p => float.Parse(p.strValue));
    }
    
    private void Init_mapData_Type_Is_int()
    {
        var arrLocal = listData.Where(x => x.strType == "int");
        this.mapData_Type_Is_int = arrLocal.ToDictionary(p => p.eGlobalKey_int, p => int.Parse(p.strValue));
    }
}

public enum EGlobalKey_float
{
    
    /// <summary>
    /// 플롯설명
    /// </summary>
    floatValue,
}

public enum EGlobalKey_string
{
    
    /// <summary>
    /// 스트링설명
    /// </summary>
    stringValue,
    
    strValue22,
    
    /// <summary>
    /// test33
    /// </summary>
    test,
    
    /// <summary>
    /// Test4444
    /// </summary>
    Test44,
}

public enum EGlobalKey_int
{
    
    /// <summary>
    /// 인트설명
    /// </summary>
    intValue,
    
    /// <summary>
    /// 인트설명22
    /// </summary>
    intValue22,
}

#region 
static
public class global_ContainerHelper
{
    
    public static string Getstring(this EGlobalKey_string eKey, System.Action<string> OnError = null)
    {
          string pData;
          if(global_Container.instance.mapData_Type_Is_string.TryGetValue(eKey, out pData) == false)
          {
              if(OnError != null)
                  OnError(nameof(global_Container) + "- Not Found Data // Key : " + eKey);
          }
          return pData;
    }
    
    public static float Getfloat(this EGlobalKey_float eKey, System.Action<string> OnError = null)
    {
          System.Single pData;
          if(global_Container.instance.mapData_Type_Is_float.TryGetValue(eKey, out pData) == false)
          {
              if(OnError != null)
                  OnError(nameof(global_Container) + "- Not Found Data // Key : " + eKey);
          }
          return pData;
    }
    
    public static int Getint(this EGlobalKey_int eKey, System.Action<string> OnError = null)
    {
          System.Int32 pData;
          if(global_Container.instance.mapData_Type_Is_int.TryGetValue(eKey, out pData) == false)
          {
              if(OnError != null)
                  OnError(nameof(global_Container) + "- Not Found Data // Key : " + eKey);
          }
          return pData;
    }
}
#endregion
