//------------------------------------------------------------------------------
// Author : Strix
// Github : https://github.com/KorStrix/SheetParser
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using UnityEngine;



public class UnitySO_Container : UnityEngine.ScriptableObject
{
    
    public List<UnitySO> listData;
    
    public Dictionary<int, UnitySO> mapData_Key_Is_intValue;
    
    public Dictionary<string, List<UnitySO>> mapData_Key_Is_strAutoEnum;
    
    public Dictionary<AutoEnumTest, UnitySO> mapData_Key_Is_AutoEnumValue;
    
    public void DoInit(bool bIsUpdateChildAsset)
    {
#if UNITY_EDITOR
        if(bIsUpdateChildAsset)
        {
           listData.Clear();
           Object[] arrObject = UnityEditor.AssetDatabase.LoadAllAssetRepresentationsAtPath(UnityEditor.AssetDatabase.GetAssetPath(this));
           for (int i = 0; i < arrObject.Length; i++)
               listData.Add((UnitySO)arrObject[i]);
           UnityEditor.EditorUtility.SetDirty(this);
        }
#endif
        this.Init_mapData_Key_Is_intValue();
        this.Init_mapData_Key_Is_strAutoEnum();
        this.Init_mapData_Key_Is_AutoEnumValue();
    }
    
    private void Init_mapData_Key_Is_intValue()
    {
        this.mapData_Key_Is_intValue = listData.ToDictionary(x => x.intValue);
    }
    
    private void Init_mapData_Key_Is_strAutoEnum()
    {
        var arrLocal = listData.GroupBy(x => x.strAutoEnum);
        this.mapData_Key_Is_strAutoEnum = arrLocal.ToDictionary(g => g.Key, g => g.ToList());
    }
    
    private void Init_mapData_Key_Is_AutoEnumValue()
    {
        this.mapData_Key_Is_AutoEnumValue = listData.ToDictionary(x => x.AutoEnumValue);
    }
}

public enum AutoEnumTest
{
    
    AutoEnum_1,
    
    AutoEnum_2,
    
    AutoEnum_3,
}
