//------------------------------------------------------------------------------
// Author : Strix
// Github : https://github.com/KorStrix/SheetParser
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using UnityEngine;



public class UnitySO2_Container : UnityEngine.ScriptableObject
{
    
    public List<UnitySO2> listData;
    
    public void DoInit(bool bIsUpdateChildAsset)
    {
#if UNITY_EDITOR
        if(bIsUpdateChildAsset)
        {
           listData.Clear();
           Object[] arrObject = UnityEditor.AssetDatabase.LoadAllAssetRepresentationsAtPath(UnityEditor.AssetDatabase.GetAssetPath(this));
           for (int i = 0; i < arrObject.Length; i++)
               listData.Add((UnitySO2)arrObject[i]);
           UnityEditor.EditorUtility.SetDirty(this);
        }
#endif
    }
}
