//------------------------------------------------------------------------------
// Author : Strix
// Github : https://github.com/KorStrix/SheetParser
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;



public class UnitySO : UnityEngine.ScriptableObject
{
    
    public string MaterialPath;
    
    public string strComment;
    
    public int intValue;
    
    public string strAutoEnum;
    
    public AutoEnumTest AutoEnumValue;
    
    public UnitySO2 pOtherSO;
}
