//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using UnityEngine;



public enum AutoEnumTest
{
    
    AutoEnum_1,
    
    AutoEnum_2,
    
    AutoEnum_3,
}

public struct struct1
{
    
    public int Int;
    
    public string stringmember;
    
    public TestEnum enummember;
}

public enum TestEnum
{
    
    /// <summary>
    /// 마이너스일
    /// </summary>
    Minus_One = -1,
    
    /// <summary>
    /// 제로
    /// </summary>
    Zero = 0,
    
    /// <summary>
    /// 원
    /// </summary>
    One = 1,
}

public enum TestEnum2
{
    
    /// <summary>
    /// 111
    /// </summary>
    MO = -1,
    
    /// <summary>
    /// 0
    /// </summary>
    ZO = 0,
    
    /// <summary>
    /// 11
    /// </summary>
    O = 1,
}

public enum TestEnum3
{
    
    A,
}
