//------------------------------------------------------------------------------
// Author : Strix
// Github : https://github.com/KorStrix/SheetParser
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using UnityEngine;



public class UnitySO_Container : UnityEngine.ScriptableObject
{
    
    public List<UnitySO> listData;
    
    public Dictionary<int, UnitySO> mapData_Key_Is_intValue;
    
    public Dictionary<string, List<UnitySO>> mapData_Key_Is_strAutoEnum;
    
    public Dictionary<AutoEnumTest, UnitySO> mapData_Key_Is_AutoEnumValue;
    
    public void DoInit()
    {
#if UNITY_EDITOR
        listData.Clear();
        Object[] arrObject = UnityEditor.AssetDatabase.LoadAllAssetRepresentationsAtPath(UnityEditor.AssetDatabase.GetAssetPath(this));
        for (int i = 0; i < arrObject.Length; i++)
           listData.Add((UnitySO)arrObject[i]);
       UnityEditor.EditorUtility.SetDirty(this);
#endif
        this.Init_mapData_Key_Is_intValue();
        this.Init_mapData_Key_Is_strAutoEnum();
        this.Init_mapData_Key_Is_AutoEnumValue();
    }
    
    private void Init_mapData_Key_Is_intValue()
    {
        this.mapData_Key_Is_intValue = listData.ToDictionary(x => x.intValue);
    }
    
    private void Init_mapData_Key_Is_strAutoEnum()
    {
        var arrLocal = listData.GroupBy(x => x.strAutoEnum);
        this.mapData_Key_Is_strAutoEnum = arrLocal.ToDictionary(g => g.Key, g => g.ToList());
    }
    
    private void Init_mapData_Key_Is_AutoEnumValue()
    {
        this.mapData_Key_Is_AutoEnumValue = listData.ToDictionary(x => x.AutoEnumValue);
    }
}
