//------------------------------------------------------------------------------
// Author : Strix
// Github : https://github.com/KorStrix/Google_SpreadSheetParser
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using UnityEngine;



public class UnitySO2 : ScriptableObject
{
    
    public string strComment;
    
    public UnitySO pUnitySO;
}
